# Generated by Django 6.0.4 on 2026-05-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('color_class', models.CharField(default='bg-blue-100 text-blue-800', help_text='Clases Tailwind para el chip de color del departamento', max_length=80, verbose_name='clase de color Tailwind')),
                ('icon', models.CharField(blank=True, default='groups', max_length=60, verbose_name='ícono Material Symbols')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='responsibles/', verbose_name='foto')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibles', to='calendar_app.department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('scope', models.CharField(choices=[('local', 'Local'), ('association', 'Asociación'), ('union', 'Unión'), ('general', 'General')], default='local', max_length=20, verbose_name='alcance')),
                ('event_type', models.CharField(choices=[('service', 'Culto'), ('seminar', 'Seminario'), ('meeting', 'Reunión'), ('social', 'Social'), ('youth', 'Jóvenes'), ('children', 'Infantil'), ('outreach', 'Evangelismo'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo de evento')),
                ('audience', models.CharField(choices=[('all', 'Todo público'), ('members', 'Miembros'), ('leaders', 'Directivos'), ('youth', 'Jóvenes'), ('children', 'Niños'), ('women', 'Mujeres'), ('men', 'Varones')], default='all', max_length=20, verbose_name='público')),
                ('start_datetime', models.DateTimeField(verbose_name='inicio')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='término')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='todo el día')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='lugar')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='requiere inscripción')),
                ('registration_url', models.URLField(blank=True, verbose_name='URL de inscripción')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='imagen de portada')),
                ('bible_verse', models.CharField(blank=True, max_length=300, verbose_name='versículo bíblico')),
                ('administrative_note', models.TextField(blank=True, verbose_name='nota administrativa')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.department', verbose_name='departamento')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.responsible', verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['start_datetime'],
            },
        ),
    ]
