# Generated by Django 6.0.4 on 2026-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='color_class',
        ),
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#4f46e5', help_text='Color hexadecimal del departamento, ej: #7c3aed', max_length=20, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('all', 'Todo público'), ('members', 'Miembros'), ('leaders', 'Directivos'), ('youth', 'Jóvenes'), ('juveniles', 'Juveniles'), ('intermediaries', 'Intermediarios'), ('children', 'Niños'), ('women', 'Mujeres'), ('men', 'Varones')], default='all', max_length=20, verbose_name='público'),
        ),
    ]
