import { DataSource } from 'typeorm';
import { Hymn } from '../../modules/worship-services/entities/hymn.entity';
import { Seeder } from '../seeder';

export class HymnSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const repo = dataSource.getRepository(Hymn);

    const hymns = [
      { number: 1, name: 'Cantad Alegres al Señor' },
      { number: 2, name: 'Dá Gloria al Señor' },
      { number: 3, name: 'Unidos en Espíritu' },
      { number: 4, name: 'Alabanzas sin Cesar' },
      { number: 5, name: 'A Ti Glorioso Dios' },
      { number: 6, name: 'Hosanna' },
      { number: 7, name: 'Oh Dios Mi Soberano Rey' },
      { number: 8, name: 'Suenen Dulces Himnos' },
      { number: 9, name: 'Alabemos al Señor' },
      { number: 10, name: 'Alaba al Dios de Abraham' },
      { number: 11, name: 'Alma Bendice al Señor' },
      { number: 12, name: 'Todos Juntos Reunidos' },
      { number: 13, name: 'Al Dios Invisible' },
      { number: 14, name: 'Engrandecido sea Dios' },
      { number: 15, name: 'Loamoste ¡Oh Dios!' },
      { number: 16, name: 'A Nuestro Padre Dios' },
      { number: 17, name: 'Oh Padre Eterno Dios' },
      { number: 18, name: 'Load al Padre' },
      { number: 19, name: 'Padre Nuestro' },
      { number: 20, name: 'A Dios el Padre' },
      { number: 21, name: 'Gloria sea al Padre' },
      { number: 22, name: 'Jehová Está en Su Santo Templo' },
      { number: 23, name: 'Silencio Silencio' },
      { number: 24, name: 'Imploramos Tu Presencia' },
      { number: 25, name: 'Siento la Presencia del Señor' },
      { number: 26, name: 'Aquí Reunidos' },
      { number: 27, name: '¡Oh Pastor Divino, Escucha!' },
      { number: 28, name: 'Tu Pueblo Jubiloso' },
      { number: 29, name: 'Del Culto el Tiempo Llega' },
      { number: 30, name: 'Abre Mis Ojos' },
      { number: 31, name: '¡Oh, Señor! Al Orar' },
      { number: 32, name: 'Nos Reunimos en Tu Santuario' },
      { number: 33, name: 'Tu Presencia Padre Amante, Invocamos' },
      { number: 34, name: 'En Momentos Así' },
      { number: 35, name: 'Oye, Oh Señor' },
      { number: 36, name: '¡Oh, Dios, Que Oyes Cada Oración!' },
      { number: 37, name: 'Dios Os Guarde' },
      { number: 38, name: 'Que Dios Te Guarde' },
      { number: 39, name: 'Despide Hoy Tu Grey' },
      { number: 40, name: 'Shalom' },
      { number: 41, name: 'Gracia, Amor y Comunión' },
      { number: 42, name: 'Queda, Señor' },
      { number: 43, name: 'Agua de Vida' },
      { number: 44, name: 'Despídenos con Tu Bendición' },
      { number: 45, name: 'Después, Señor' },
      { number: 46, name: 'Hoy Amanece' },
      { number: 47, name: 'Por la Mañana' },
      { number: 48, name: 'Oh Dios, Si He Ofendido un Corazón' },
      { number: 49, name: 'Cristo, Ya la Noche Cierra' },
      { number: 50, name: 'Baja el Sol' },
      { number: 51, name: 'Nuestro Sol Se Poné Ya' },
      { number: 52, name: 'Señor Jesús, el Día Ya se Fue' },
      { number: 53, name: '¡Oh Amor de Dios!' },
      { number: 54, name: 'Tan Bueno es Dios' },
      { number: 55, name: 'Grande, Señor, es Tu Misericordia' },
      { number: 56, name: 'De Tal Manera Amó' },
      { number: 57, name: 'Mi Dios Me Ama' },
      { number: 58, name: 'Grande es el Amor Divino' },
      { number: 59, name: 'Mirad Qué Amor' },
      { number: 60, name: '¡Santo! ¡Santo! ¡Santo! Tu Gloria Llena' },
      { number: 61, name: 'Santo, Santo, Santo, Dios Omnipotente' },
      { number: 62, name: 'Santo, Santo, Santo, Santo es el Señor' },
      { number: 63, name: 'Al Rey Adorad' },
      { number: 64, name: 'Yo Canto el Poder de Dios' },
      { number: 65, name: 'El Mundo es de Mi Dios' },
      { number: 66, name: '¿Sabes Cuántos?' },
      { number: 67, name: '¡Señor, Yo Te Conozco!' },
      { number: 68, name: 'Todo lo que Ha Creado Dios' },
      { number: 69, name: 'Señor, Mi Dios' },
      { number: 70, name: '¡Nuestro Dios Reina!' },
      { number: 71, name: 'Cada Cosa Hermosa' },
      { number: 72, name: 'Fue un Milagro' },
      { number: 73, name: 'La Creación' },
      { number: 74, name: 'Himno al Creador' },
      { number: 75, name: 'Grande es Jeová' },
      { number: 76, name: 'Eterno Dios, Mi Creador' },
      { number: 77, name: 'Sea Exaltado' },
      { number: 78, name: '¡Al Mundo Paz!' },
      { number: 79, name: 'Se Oye un Canto en Alta Esfera' },
      { number: 80, name: 'Venid, Pastorcillos' },
      { number: 81, name: 'Noche de Paz' },
      { number: 82, name: 'Ya Repican las Campanas' },
      { number: 83, name: 'La Primera Navidad' },
      { number: 84, name: 'Ve, Dilo en las Montañas' },
      { number: 85, name: 'Allá en el Pesebre' },
      { number: 86, name: 'A Medianoche en Belén' },
      { number: 87, name: 'Venid, Fieles Todos' },
      { number: 88, name: 'Oh, Aldehuela de Belén' },
      { number: 89, name: 'Cristianos, Alegrabos Hoy' },
      { number: 90, name: 'Somos del Oriente' },
      { number: 91, name: '¿Qué Niño es Este?' },
      { number: 92, name: 'Ángeles Cantando Estén' },
      { number: 93, name: 'Hubo Uno que Quiso' },
      { number: 94, name: 'Sangró Mi Soberano Dios' },
      { number: 95, name: 'Un Día' },
      { number: 96, name: 'Al Contemplar la Excelsa Cruz' },
      { number: 97, name: 'En el Monte Calvario' },
      { number: 98, name: 'Rostro Divino' },
      { number: 99, name: 'Jamás Podrá Alguien Separarnos' },
      { number: 100, name: '¡Dulces Momentos!' },
      { number: 101, name: 'Cabeza Sacrosanta' },
      { number: 102, name: 'Cordero de Dios' },
      { number: 103, name: 'Jesús Resucitado' },
      { number: 104, name: 'La Tumba le Encerró' },
      { number: 105, name: 'Cristo Ha Resucitado' },
      { number: 106, name: 'Tuya es la Gloria' },
      { number: 107, name: 'Canto el Gran Amor' },
      { number: 108, name: 'Amigo Fiel es Cristo' },
      { number: 109, name: 'Un Buen Amigo Tengo Yo' },
      { number: 110, name: 'Cristo es el Mejor Amigo' },
      { number: 111, name: 'Como Jesús No Hay Otro Amigo' },
      { number: 112, name: 'Ningún Otro Me Amó Cual Cristo' },
      { number: 113, name: 'Amor que No Me Dejarás' },
      { number: 114, name: 'Dime la Antigua Historia' },
      { number: 115, name: '¡Oh, Cuán Grande Amor!' },
      { number: 116, name: 'Cristo Está a Mi Lado' },
      { number: 117, name: 'No Sé Por Qué' },
      { number: 118, name: 'Cuando Estés Cansado y Abatido' },
      { number: 119, name: 'De Su Trono, Mi Jesús' },
      { number: 120, name: '¡Cuánto Me Alegra!' },
      { number: 121, name: 'Es Jesucristo la Vida, la Luz' },
      { number: 122, name: 'Divino Pastor' },
      { number: 123, name: '¡Cuánto Nos Ama Jesús!' },
      { number: 124, name: 'Ama el Pastor Sus Ovejas' },
      { number: 125, name: 'Infinito Amor de Cristo' },
      { number: 126, name: 'Abrigadas y Salvas en el Redil' },
      { number: 127, name: 'Cristo, Nombre Dulce' },
      { number: 128, name: '¡Tu Nombre es Dulce, Buen Jesús!' },
      { number: 129, name: 'Cual Jesús No Hay Otro Nombre' },
      { number: 130, name: 'Cristo, Cristo, Cristo' },
      { number: 131, name: 'Bendito es el Nombre de Jesús' },
      { number: 132, name: 'Dulce, Hermoso Nombre es Jesús' },
      { number: 133, name: 'Venid, con Cánticos Venid' },
      { number: 134, name: 'Cual Mirra Fragante' },
      { number: 135, name: 'Cristo, Nombre Sublime' },
      { number: 136, name: '¡Oh, Cuánto Amo a Cristo!' },
      { number: 137, name: 'De Jesús el Nombre Invoca' },
      { number: 138, name: 'De Mi Amante Salvador' },
      { number: 139, name: 'La Tierna Voz del Salvador' },
      { number: 140, name: 'Te Quiero, Te Quiero' },
      { number: 141, name: '¡Alabadle!' },
      { number: 142, name: 'Venid, Cantad de Gozo en Plenitud' },
      { number: 143, name: 'Digno Eres Tú' },
      { number: 144, name: 'Mi Salvador' },
      { number: 145, name: 'Con Acentos de Alegría' },
      { number: 146, name: 'Ni en la Tierra' },
      { number: 147, name: 'A Dios Sea Gloria' },
      { number: 148, name: 'Solo Cristo' },
      { number: 149, name: 'Junto a la Cruz do Jesús Murió' },
      { number: 150, name: 'A Cristo Doy Mi Canto' },
      { number: 151, name: 'Por Eso Lo Amo' },
      { number: 152, name: 'A Ti, Jesús' },
      { number: 153, name: 'Ved a Cristo' },
      { number: 154, name: 'Dad Gloria al Cordero Rey' },
      { number: 155, name: 'En Sion Jesús Hoy Reina' },
      { number: 156, name: 'A Cristo Coronad' },
      { number: 157, name: '¡Majestad!' },
      { number: 158, name: 'Amanece Ya la Mañana de Oro' },
      { number: 159, name: 'Yo Espero la Mañana' },
      { number: 160, name: 'Viene Otra Vez Nuestro Salvador' },
      { number: 161, name: '¡Oh! Cuán Gratas las Nuevas' },
      { number: 162, name: 'En Presencia Estar de Cristo' },
      { number: 163, name: 'Cristo Viene, Esto es Cierto' },
      { number: 164, name: 'Jesús Pronto Volverá' },
      { number: 165, name: '¡Vendrá el Señor!' },
      { number: 166, name: 'Siervos de Dios, la Trompeta Tocad' },
      { number: 167, name: '¿Quién en Deslumbrante Gloria?' },
      { number: 168, name: 'El Rey que Viene' },
      { number: 169, name: 'Cuando Suene la Trompeta' },
      { number: 170, name: 'La Segunda Venida de Cristo' },
      { number: 171, name: '¿Has Oído el Mensaje?' },
      { number: 172, name: 'Promesa Dulce' },
      { number: 173, name: '¿Será al Albor?' },
      { number: 174, name: 'Mira los Hitros' },
      { number: 175, name: 'Ved a Cristo, que Se Acerca' },
      { number: 176, name: 'Tú Verás al Rey Viniedo' },
      { number: 177, name: 'Los Tres Mensajes Angélicos' },
      { number: 178, name: 'Contemplé la Gloria' },
      { number: 179, name: '¡Cristo Viene! Aquel Día Se Acerca' },
      { number: 180, name: 'Sí, Lo Veremos' },
      { number: 181, name: 'Una Esperanza' },
      { number: 182, name: 'Veremos a Cristo' },
      { number: 183, name: 'No Me He Olvidado de Ti' },
      { number: 184, name: 'Nunca Te Rindas' },
      { number: 185, name: 'Al Cielo Voy' },
      { number: 186, name: 'Hace Años Escuché' },
      { number: 187, name: 'Aunque Anochezca' },
      { number: 188, name: 'Gran Alegría' },
      { number: 189, name: 'Cristo Muy Pronto Vendrá' },
      { number: 190, name: 'Santo Espíritu de Cristo' },
      { number: 191, name: 'La Nueva Proclamad' },
      { number: 192, name: 'Llena Mi Ser' },
      { number: 193, name: 'Dios Nos Ha Dado Promesa' },
      { number: 194, name: 'Vive en Mí' },
      { number: 195, name: 'Abre Mis Ojos a la Luz' },
      { number: 196, name: 'Santo Espíritu de Dios' },
      { number: 197, name: 'Dulce Espíritu' },
      { number: 198, name: 'Ven, Señor Jesús' },
      { number: 199, name: 'Movidos por Tu Espíritu' },
      { number: 200, name: 'Bautízanos Hoy' },
      { number: 201, name: 'Canción del Espíritu' },
      { number: 202, name: 'Danos el Fuego' },
      { number: 203, name: 'Santo Espíritu Llena Mi Vida' },
      { number: 204, name: 'Oh, Cantádmelas Otra Vez' },
      { number: 205, name: 'Dadme la Biblia' },
      { number: 206, name: 'Padre, Tu Palabra es Mi Delicia' },
      { number: 207, name: 'Dios Nos Habla' },
      { number: 208, name: '¡Santa Biblia!' },
      { number: 209, name: 'La Biblia Nos Habla de Cristo' },
      { number: 210, name: 'Huye Cual Ave' },
      { number: 211, name: 'Fija Tus Ojos en Cristo' },
      { number: 212, name: 'A Tu Puerta Cristo Está' },
      { number: 213, name: 'Tierno y Amante, Jesús Nos Invita' },
      { number: 214, name: 'Mientras Jesús Te Llama' },
      { number: 215, name: 'Con Voz Benigna Te Llama Jesús' },
      { number: 216, name: 'Dios al Pródigo Llama' },
      { number: 217, name: 'Bienvenida Da Jesús' },
      { number: 218, name: 'A Jesucristo Ven Sin Tardar' },
      { number: 219, name: 'Tan Triste y Tan Lejos de Dios' },
      { number: 220, name: 'Allá la Puerta Abierta Está' },
      { number: 221, name: 'Puertas Abiertas Encontrarán' },
      { number: 222, name: 'Del Trono Celestial' },
      { number: 223, name: 'Oí la Voz del Salvador' },
      { number: 224, name: 'Oí la Voz del Buen Jesús' },
      { number: 225, name: 'Un Hombre Llegóse de Noche a Jesús' },
      { number: 226, name: 'Buscad Primero' },
      { number: 227, name: 'Preste Oídos el Humano' },
      { number: 228, name: 'Me Buscaréis y Me Hallaréis' },
      { number: 229, name: '¿Has Pensado lo que Puede Costar?' },
      { number: 230, name: 'Abre Tu Corazón' },
      { number: 231, name: 'Todo en el Altar' },
      { number: 232, name: 'Entrégate en Oración' },
      { number: 233, name: 'Ven a la Fuente de Vida' },
      { number: 234, name: '¿Temes que en la Lucha?' },
      { number: 235, name: 'La Razón de Vivir' },
      { number: 236, name: 'A Jesús Entrega Todo' },
      { number: 237, name: 'Jesús Hoy Espera Entrar en Tu Ser' },
      { number: 238, name: 'Yo Escucho, Buen Jesús' },
      { number: 239, name: 'De Dios Vagaba Lejos Yo' },
      { number: 240, name: 'Te Ruego, Oh Dios' },
      { number: 241, name: 'Perdón Te Ruego, Mi Señor y Dios' },
      { number: 242, name: 'Una es, Señor, Mi Petición' },
      { number: 243, name: 'Entrego Todo a Cristo' },
      { number: 244, name: 'Padre, Dios' },
      { number: 245, name: 'Cúmplase, Oh Cristo, Tu Voluntad' },
      { number: 246, name: 'Te Quiero, Mi Señor' },
      { number: 247, name: 'Yo Te Seguiré' },
      { number: 248, name: 'Que Mi Vida Entera Esté' },
      { number: 249, name: 'Tal Como Soy' },
      { number: 250, name: 'Padre, a Tus Pies Me Postro' },
      { number: 251, name: 'No Yo, Sino Él' },
      { number: 252, name: 'Dejo el Mundo' },
      { number: 253, name: 'Tuyo Soy, Jesús' },
      { number: 254, name: 'Anhelo Ser Limpio' },
      { number: 255, name: 'Oh Cristo, Te Adoro' },
      { number: 256, name: 'Jesús, Yo He Prometido' },
      { number: 257, name: '¡Oh! Ven, Te Invito, Cristo' },
      { number: 258, name: 'Tú Dejaste Tu Trono' },
      { number: 259, name: 'Mi Espíritu, Alma y Cuerpo' },
      { number: 260, name: 'Junto a la Cruz de Cristo' },
      { number: 261, name: 'Salvador, a Ti Me Rindo' },
      { number: 262, name: 'Los Tesoros del Mundo' },
      { number: 263, name: 'Entra en Este Corazón' },
      { number: 264, name: 'Un Día Más por Cristo' },
      { number: 265, name: 'La Senda Ancha Dejaré' },
      { number: 266, name: 'Vivo por Cristo' },
      { number: 267, name: 'A la Cruz de Cristo Voy' },
      { number: 268, name: 'Puedo Oír Tu Voz Llamando' },
      { number: 269, name: 'Prefiero a Mi Cristo' },
      { number: 270, name: 'Meditar en Jesús' },
      { number: 271, name: 'Hoy Me Llama el Mundo en Vano' },
      { number: 272, name: 'De Esclavitud' },
      { number: 273, name: 'Tu Vida, Oh Salvador' },
      { number: 274, name: '¿Qué Te Daré, Maestro?' },
      { number: 275, name: 'Humilde Oración' },
      { number: 276, name: 'Con Nuestras Mentes' },
      { number: 277, name: 'Amarte Más' },
      { number: 278, name: '¿Puede el Mundo Ver a Jesús en Mí?' },
      { number: 279, name: 'Transfórmame a Tu Imagen' },
      { number: 280, name: 'Ser Semejante a Jesús' },
      { number: 281, name: 'He Decidido Seguir a Cristo' },
      { number: 282, name: '¡Brilla, Jesús!' },
      { number: 283, name: 'Ven, Señor Jesús' },
      { number: 284, name: 'Me Dice el Salvador' },
      { number: 285, name: 'Confío en Jesucristo' },
      { number: 286, name: 'Hay una Fuente Sin Igual' },
      { number: 287, name: 'Rey de Mi Vida' },
      { number: 288, name: 'Al Contemplarte, Mi Salvador' },
      { number: 289, name: '¿Qué Me Puede Dar Perdón?' },
      { number: 290, name: 'Fuente de la Vida Eterna' },
      { number: 291, name: 'Perdido, Fui a Mi Jesús' },
      { number: 292, name: 'Por Fe en Cristo, el Redentor' },
      { number: 293, name: '¿Quieres Ser Salvo de Toda Maldad?' },
      { number: 294, name: 'En Jesús por Fe Confío' },
      { number: 295, name: 'Las Manos, Padre' },
      { number: 296, name: 'Comprado con Sangre por Cristo' },
      { number: 297, name: 'Salvado con Sangre por Cristo' },
      { number: 298, name: 'Al Calvario, Solo, Jesús Ascendió' },
      { number: 299, name: 'Hay Vida en Mirar' },
      { number: 300, name: 'Lejos de Mi Padre Dios' },
      { number: 301, name: 'Cristo es Mi Amante Salvador' },
      { number: 302, name: 'Grato es Contar la Historia' },
      { number: 303, name: 'Sublime Gracia' },
      { number: 304, name: 'Mi Redentor, el Rey de Gloria' },
      { number: 305, name: 'Maravillosa Su Gracia es' },
      { number: 306, name: 'Llegó Jesús' },
      { number: 307, name: 'Roca de la Eternidad' },
      { number: 308, name: 'Dios Descendió' },
      { number: 309, name: 'La Voz de Jesús' },
      { number: 310, name: 'Cristo, Centro de Mi Vida' },
      { number: 311, name: 'Cuando Junte Jesús las Naciones' },
      { number: 312, name: 'Día Grande Viene' },
      { number: 313, name: 'La Hora del Juicio' },
      { number: 314, name: 'Cristo, Rey Omnipotente' },
      { number: 315, name: 'El Juicio Empezó' },
      { number: 316, name: 'Hay un Mundo Feliz Más Allá' },
      { number: 317, name: 'En el Hogar Donde Nunca Habrá' },
      { number: 318, name: 'En la Mansión de Mi Señor' },
      { number: 319, name: 'Cuando Mi Lucha Termine al Final' },
      { number: 320, name: 'Jamás Se Dice "Adiós" Allá' },
      { number: 321, name: 'Allá Sobre Montes' },
      { number: 322, name: 'Busquemos la Patria' },
      { number: 323, name: 'He de Conocerle Entonces' },
      { number: 324, name: 'Pronto Yo Veré a Jesús' },
      { number: 325, name: 'No Puede el Mundo Ser Mi Hogar' },
      { number: 326, name: 'Un Día Yo He de Falta' },
      { number: 327, name: 'Jerusalén, Mi Amado Hogar' },
      { number: 328, name: '¿Nos Veremos Junto al Río?' },
      { number: 329, name: 'En la Célica Morada' },
      { number: 330, name: 'Hay un Feliz Edén' },
      { number: 331, name: 'Alma Bendice al Señor' },
      { number: 332, name: 'En la Tierra Adonde Iré' },
      { number: 333, name: 'Aunque en Esta Vida' },
      { number: 334, name: 'Cuánto Anhelo Llegar' },
      { number: 335, name: 'Mi Hogar Celestial' },
      { number: 336, name: 'Del Bello País He Leído' },
      { number: 337, name: 'Nunca Más Adiós' },
      { number: 338, name: 'Las Riberas de Dicha Inmortal' },
      { number: 339, name: 'A Veces Oigo un Himno' },
      { number: 340, name: '¡Oh, Qué Música Divina!' },
      { number: 341, name: 'Más Cerca del Hogar' },
      { number: 342, name: 'Después del Río' },
      { number: 343, name: 'Quiero Llegar a Ser Parte del Cielo' },
      { number: 344, name: 'Entonad un Himno' },
      { number: 345, name: 'Canta, y Tus Penas se Irán' },
      { number: 346, name: '¡Feliz el Día!' },
      { number: 347, name: 'Con Gozo Canto al Señor' },
      { number: 348, name: 'Dicha Grande' },
      { number: 349, name: 'Gran Gozo Hay en Mi Alma Hoy' },
      { number: 350, name: 'Andando en la Luz de Dios' },
      { number: 351, name: 'Yo Tengo Gozo' },
      { number: 352, name: 'Gozaos, Cristo es Rey' },
      { number: 353, name: 'Suenan Melodías en Mi Ser' },
      { number: 354, name: 'Voy Caminando' },
      { number: 355, name: 'Yo Voy Feliz' },
      { number: 356, name: 'Gozo es Conocer a Cristo' },
      { number: 357, name: 'Jesús, Tú Eres Mi Alegría' },
      { number: 358, name: 'En el Seno de Mi Alma' },
      { number: 359, name: 'Regocijaos Siempre' },
      { number: 360, name: 'En Jesucristo, Mártir de Paz' },
      { number: 361, name: 'Percibe Mi Alma un Son' },
      { number: 362, name: 'Con Sin Igual Amor' },
      { number: 363, name: 'Hay un Canto Nuevo en Mi Ser' },
      { number: 364, name: 'Jesús Da Paz' },
      { number: 365, name: 'Elevemos al Señor' },
      { number: 366, name: 'En Cristo Hallo Amigo' },
      { number: 367, name: 'Gracias, Dios' },
      { number: 368, name: 'Padre Amado' },
      { number: 369, name: 'Gratitud y Alabanza' },
      { number: 370, name: 'Por la Excelsa Majestad' },
      { number: 371, name: 'Jesús Te Ama' },
      { number: 372, name: '¿Cómo Agradecer?' },
      { number: 373, name: 'Mi Redentor es Cristo' },
      { number: 374, name: 'Dulce Comunión' },
      { number: 375, name: 'Sed Puros y Santos' },
      { number: 376, name: 'Dulce Oración' },
      { number: 377, name: 'A los Pies de Jesucristo' },
      { number: 378, name: '¡Oh, Qué Amigo Nos Es Cristo!' },
      { number: 379, name: 'Habla, Señor, a Mi Alma' },
      { number: 380, name: 'Ando con Cristo' },
      { number: 381, name: 'Alma Bendice al Señor' },
      { number: 382, name: 'A Solas al Huerto Yo Voy' },
      { number: 383, name: 'Habla a Tu Dios de Mañana' },
      { number: 384, name: 'El Jardín de Oración' },
      { number: 385, name: 'Hablando con Jesús' },
      { number: 386, name: 'Hay un Lugar de Paz' },
      { number: 387, name: 'Aparte del Mundo' },
      { number: 388, name: 'Debo Decir a Cristo' },
      { number: 389, name: 'Conversar con Jesucristo' },
      { number: 390, name: 'Soy Yo, Señor' },
      { number: 391, name: '¿Le Importará a Jesús?' },
      { number: 392, name: 'Hay Quien Vela Mis Pisadas' },
      { number: 393, name: 'Mi Fe Contempla a Ti' },
      { number: 394, name: '¡Cuán Firme Cimiento!' },
      { number: 395, name: '¡Oh, Cuán Dulce es Fiar en Cristo!' },
      { number: 396, name: '¡Oh Qué Salvador!' },
      { number: 397, name: 'Oh Buen Señor, Velada Está' },
      { number: 398, name: 'Cuando Sopla Airada la Tempestad' },
      { number: 399, name: 'En Estos Tiempos' },
      { number: 400, name: 'Castillo Fuerte es Nuestro Dios' },
      { number: 401, name: 'Eterna Roca es Mi Jesús' },
      { number: 402, name: '¡Oh!, Salvo en la Roca' },
      { number: 403, name: 'Cuando en la Lucha' },
      { number: 404, name: 'A Cualquier Parte' },
      { number: 405, name: 'Sé Quién es Jesús' },
      { number: 406, name: 'Jesús es Mi Luz' },
      { number: 407, name: 'Muy Cerca de Mi Redentor' },
      { number: 408, name: 'Cristo Me Ayuda por Él a Vivir' },
      { number: 409, name: 'Si Mi Débil Fe Flaqueare' },
      { number: 410, name: 'Cuando Te Quiero' },
      { number: 411, name: 'Bajo Sus Alas' },
      { number: 412, name: 'Todas las Promesas' },
      { number: 413, name: 'Si la Carga es Pesada' },
      { number: 414, name: '¡Oh, Buen Maestro, Despierta!' },
      { number: 415, name: 'Salvo en los Tiernos Brazos' },
      { number: 416, name: '¡Oh!, Tenga Yo la Ardiente Fe' },
      { number: 417, name: 'Dame la Fe de Mi Jesús' },
      { number: 418, name: 'Padre, Yo Vengo a Ti' },
      { number: 419, name: 'Por la Justicia de Jesús' },
      { number: 420, name: 'Nunca Desmayes' },
      { number: 421, name: 'Cariñoso Salvador' },
      { number: 422, name: 'Nada Puede Ya Faltarme' },
      { number: 423, name: 'Pertenezco a Mi Rey' },
      { number: 424, name: '¿Cómo Podré Estar Triste?' },
      { number: 425, name: 'Día en Día' },
      { number: 426, name: 'Tengo Paz' },
      { number: 427, name: 'Lleva Todo Tu Cansancio a Cristo' },
      { number: 428, name: 'Su Oveja Soy' },
      { number: 429, name: 'Él Puede' },
      { number: 430, name: 'Solo No Estoy' },
      { number: 431, name: 'A Él Mis Problemas Le Doy' },
      { number: 432, name: 'Como el Ciervo' },
      { number: 433, name: 'Conmigo Marcha un Ángel' },
      { number: 434, name: 'Jesús es Mi Vida' },
      { number: 435, name: 'Dios Sabe, Dios Oye, Dios Ve' },
      { number: 436, name: 'Él Vive Hoy' },
      { number: 437, name: 'Tu Presencia, Padre Amado, Da Consuelo' },
      { number: 438, name: 'Mira hacia Dios' },
      { number: 439, name: '¡Oh!, Quién Pudiera Andar con Dios' },
      { number: 440, name: 'Quiero, Jesús, Contigo Andar' },
      { number: 441, name: 'Jesús, Te Necesito' },
      { number: 442, name: '¡Oh! ¡Maestro y Salvador!' },
      { number: 443, name: 'Hay un Lugar Donde Quiero Estar, Cerca de Ti' },
      { number: 444, name: 'No Me Pasas' },
      { number: 445, name: 'Más de Jesús' },
      { number: 446, name: 'Más Cerca, Oh Dios, de Ti' },
      { number: 447, name: 'Más Santidad Dame' },
      { number: 448, name: 'Salvador, Mi Bien Eterno' },
      { number: 449, name: 'Cristo, Mi Piloto Sé' },
      { number: 450, name: '¡Oh Jesús, Pastor Divino!' },
      { number: 451, name: 'Cerca, Más Cerca' },
      { number: 452, name: 'Contigo Quiero Andar' },
      { number: 453, name: 'Cómo Ser Cual Cristo' },
      { number: 454, name: 'Yo Quisiera Andar con Cristo' },
      { number: 455, name: 'Mi Mano Ten' },
      { number: 456, name: 'Como la Mujer de Junto al Pozo' },
      { number: 457, name: 'More en Mí la Belleza del Salvador' },
      { number: 458, name: 'Orad por Mí' },
      { number: 459, name: 'Háblame Más de Cristo' },
      { number: 460, name: 'Quiero Estar Cerca de Cristo' },
      { number: 461, name: 'A Tu Lado Anhelo Estar' },
      { number: 462, name: 'Dame a Cristo' },
      { number: 463, name: 'Mi Oración' },
      { number: 464, name: 'Ven, Inspíranos' },
      { number: 465, name: 'Ven Junto a Mí' },
      { number: 466, name: 'Guíame, ¡oh Salvador!' },
      { number: 467, name: '¡Siempre el Salvador Conmigo!' },
      { number: 468, name: 'Paso a Paso Dios Me Guía' },
      { number: 469, name: 'Jesús Me Guía' },
      { number: 470, name: 'Guíame, Dios' },
      { number: 471, name: 'Condúceme, Maestro' },
      { number: 472, name: 'Jesús, Mi Guía es' },
      { number: 473, name: 'Háblame, y Hablaré' },
      { number: 474, name: '¿Qué Me Importan?' },
      { number: 475, name: 'El Camino es Escarpado' },
      { number: 476, name: '¿Muy Lejos el Hogar Está?' },
      { number: 477, name: 'Los Que Aman al Señor' },
      { number: 478, name: 'Sé Fiel Siempre, Hermano' },
      { number: 479, name: 'De la Mano, Señor' },
      { number: 480, name: 'Digno Eres, Oh Señor' },
      { number: 481, name: 'Voy al Cielo' },
      { number: 482, name: 'Quiero Cantar' },
      { number: 483, name: 'Cuando al Cielo Lleguemos' },
      { number: 484, name: 'Busca al Señor' },
      { number: 485, name: 'Unidos en Verdad' },
      { number: 486, name: 'En los Pasos de Jesús' },
      { number: 487, name: 'Cristo, Eres Justo Rey' },
      { number: 488, name: 'Al Andar con Jesús' },
      { number: 489, name: 'Solo Anhelo, Cristo Amado' },
      { number: 490, name: 'Mejor que los Sacrificios' },
      { number: 491, name: 'Levántate, Cristiano' },
      { number: 492, name: '¡Trabajad! ¡Trabajad!' },
      { number: 493, name: 'Hoy Quiero Trabajar Contigo' },
      { number: 494, name: 'Cerca un Alma Agobiada Está' },
      { number: 495, name: 'Mi Deber' },
      { number: 496, name: 'Sus Manos Somos' },
      { number: 497, name: 'Manos' },
      { number: 498, name: 'Puedes Demostrar con Tus Manos' },
      { number: 499, name: 'Jesús Anduvo por Aquí' },
      { number: 500, name: 'Hazme Tu Siervo' },
      { number: 501, name: 'Mi Vida al Servicio de Dios' },
      { number: 502, name: 'Brilla en el Sitio Donde Estés' },
      { number: 503, name: 'Oh Dios, Que Deseas la Vida' },
      { number: 504, name: 'Señor de Todos' },
      { number: 505, name: 'Hijo del Reino' },
      { number: 506, name: '¡De Pie, De Pie, Cristianos!' },
      { number: 507, name: 'Tentado, No Cedas' },
      { number: 508, name: 'Contendamos Siempre por Nuestra Fe' },
      { number: 509, name: '¡Firmes! ¡Fuertes!' },
      { number: 510, name: '¿Quién Está por Cristo?' },
      { number: 511, name: 'Marcharé en la Divina Luz' },
      { number: 512, name: 'Nunca Estéis Desanimados' },
      { number: 513, name: 'Honra al Hombre de Valor' },
      { number: 514, name: '¡Despertad, Despertad, Oh Cristianos!' },
      { number: 515, name: 'Despliegue el Cristiano Su Santa Bandera' },
      { number: 516, name: '¡Firmes y Adelante!' },
      { number: 517, name: 'De Pie, Oh Grey de Dios' },
      { number: 518, name: 'Jesús Está Buscando Voluntarios Hoy' },
      { number: 519, name: 'Despierta, Hermano, Sin Demorar' },
      { number: 520, name: '¡Adelante! Manda el Señor' },
      { number: 521, name: 'Al Cristo Ved' },
      { number: 522, name: 'Suenen las Palabras' },
      { number: 523, name: 'Los Sabios Dan Su Ciencia' },
      { number: 524, name: 'Traían en Silencio Presentes al Señor' },
      { number: 525, name: 'Con Gratitud, Llegamos' },
      { number: 526, name: 'Oh, Mi Patria, Te Prometo Hoy' },
      { number: 527, name: 'Señor Jehova, Omnipotente Dios' },
      { number: 528, name: 'Por Montañas, Muy Cansado' },
      { number: 529, name: 'Iglesia de Cristo' },
      { number: 530, name: 'Somos un Pequeño Pueblo Muy Feliz' },
      { number: 531, name: 'La Familia de Dios' },
      { number: 532, name: 'Sagrado es el Amor' },
      { number: 533, name: 'Cuán Bueno y Agradable' },
      { number: 534, name: 'En Tu Nombre Comenzamos' },
      { number: 535, name: 'Las Faenas Terminadas' },
      { number: 536, name: 'En Sombras de la Tarde' },
      { number: 537, name: 'Sábado Santo' },
      { number: 538, name: 'Hoy es Día de Reposo' },
      { number: 539, name: '¡Oh, Día Delicioso!' },
      { number: 540, name: 'Ya Asoma el Sol Brillante' },
      { number: 541, name: 'Señor, Reposamos' },
      { number: 542, name: 'Amo Tu Sábado' },
      { number: 543, name: 'No Te Olvides Nunca del Día del Señor' },
      { number: 544, name: 'Hoy el Sábado Glorioso' },
      { number: 545, name: 'Santo Día' },
      { number: 546, name: 'Santo Sábado, Bendito' },
      { number: 547, name: 'Sábado es' },
      { number: 548, name: 'Mi Corazón Se Llena de Alegría' },
      { number: 549, name: 'Ya el Fin Se Acerca' },
      { number: 550, name: 'Día Santo del Señor' },
      { number: 551, name: 'Embajador Soy de Mi Rey' },
      { number: 552, name: '¡Oh!, Cuánto Necesita' },
      { number: 553, name: '¿Os Pusisteis a Arar?' },
      { number: 554, name: 'Con Cristo Avanza Hoy' },
      { number: 555, name: 'Hoy Gozoso Medito' },
      { number: 556, name: 'Yo Quiero Siempre Brillar' },
      { number: 557, name: '¿Qué Estás Haciendo por Cristo?' },
      { number: 558, name: 'Ama a Tus Prójimos' },
      { number: 559, name: 'No Te Dé Temor' },
      { number: 560, name: 'Cristo Está Buscando Obreros' },
      { number: 561, name: 'Oigo del Señor la Voz Llamando' },
      { number: 562, name: 'Esparcid la Luz de Cristo' },
      { number: 563, name: 'Escuchad, Jesús Nos Dice' },
      { number: 564, name: 'Pronto la Noche Viene' },
      { number: 565, name: '¡Ve, Ve Oh Sion!' },
      { number: 566, name: 'Centinelas del Maestro' },
      { number: 567, name: 'Si en Valles de Peligros' },
      { number: 568, name: 'Hay Lugar en la Amplia Viña' },
      { number: 569, name: 'Id y Predicad el Evangelio' },
      { number: 570, name: 'Voluntario del Señor' },
      { number: 571, name: 'La Historia de Cristo Contemos' },
      { number: 572, name: 'Pescadores de Hombres' },
      { number: 573, name: 'Te Envío a Ti' },
      { number: 574, name: 'Testimonio' },
      { number: 575, name: 'Tocad Trompeta Ya' },
      { number: 576, name: 'Proclamo Hoy Que Soy Cristiano' },
      { number: 577, name: 'Yo Quiero Trabajar' },
      { number: 578, name: 'El Pueblo Que Conoce a Su Dios' },
      { number: 579, name: 'La Fuente Veo' },
      { number: 580, name: 'Las Aguas del Bautismo' },
      { number: 581, name: 'El Pan de Vida Soy' },
      { number: 582, name: 'Hoy Venimos Cual Hermanos' },
      { number: 583, name: 'La Cena de la Comunión' },
      { number: 584, name: 'Amémonos, Hermanos' },
      { number: 585, name: 'Loamoste ¡Oh Dios!' },
      { number: 586, name: 'En Memoria de Mí' },
      { number: 587, name: 'Te Dedicamos, Oh Señor' },
      { number: 588, name: 'Ven, Alma Que Lloras' },
      { number: 589, name: 'Perfecto Amor' },
      { number: 590, name: 'Guía a Ti, Señor' },
      { number: 591, name: 'Todo es Bello en el Hogar' },
      { number: 592, name: 'Si Dios Está, ¡Feliz Hogar!' },
      { number: 593, name: 'Hogar de Mis Recuerdos' },
      { number: 594, name: 'Señor, Gracias por Mi Hogar' },
      { number: 595, name: 'Feliz Hogar' },
      { number: 596, name: 'Edificamos Familias' },
      { number: 597, name: 'Oración por un Niño' },
      { number: 598, name: 'Cristo, Yo Te Seguiré' },
      { number: 599, name: 'En Este Bello Día' },
      { number: 600, name: 'Cuando Venga Jesucristo' },
      { number: 601, name: 'Cuando Leo en la Biblia' },
      { number: 602, name: 'Es el Amor Divino' },
      { number: 603, name: 'Yo Temprano Busco a Cristo' },
      { number: 604, name: 'Bellas las Manitas Son' },
      { number: 605, name: 'Jesús Tiene Tiempo' },
      { number: 606, name: 'Llama Jesús, el Buen Pastor' },
      { number: 607, name: 'Nítido Rayo por Cristo' },
      { number: 608, name: 'Corazones Siempre Alegres' },
      { number: 609, name: '¡Oh Jóvenes, Venid!' },
      { number: 610, name: 'Escuchamos Tu Llamada' },
      { number: 611, name: 'Oh, Juventud del Rey' },
      { number: 612, name: 'Jesús Te Necesita Hoy' },
      { number: 613, name: 'Hoy Nos Toca Trabajar' },
    ];

    let created = 0;
    let updated = 0;

    for (const hymnData of hymns) {
      const existing = await repo.findOne({
        where: { number: hymnData.number },
      });
      if (existing) {
        existing.name = hymnData.name;
        await repo.save(existing);
        updated++;
      } else {
        const hymn = repo.create(hymnData);
        await repo.save(hymn);
        created++;
      }
    }

    console.log(`HymnSeeder: ${created} created, ${updated} updated`);
  }
}