export enum Department {
  JA = 'jovenes_adventistas',
  ASA = 'asa',
  MinisterioInfantil = 'ministerio_infantil',
  GTeen = 'gteen',
  Aventureros = 'aventureros',
  HogarFamilia = 'hogar_y_familia',
  MIPES = 'mipes',
  ADRA = 'adra',
  MinisterioMujer = 'ministerio_de_la_mujer',
  Colportores = 'colportores',
  EducacionAdventista = 'educacion_adventista',
  EscuelaSabatica = 'escuela_sabatica',
  Musica = 'musica',
  Salud = 'salud',
  Comunicaciones = 'comunicaciones',
}
